### ISSUE TITLE
Wg

### ISSUE THREAD

**Issue by markuznw** [JuliusBairaktaris/Qualcommax_NSS_Builder#1]
Hello, can you add wireguard please? Thanks

**Comment by starraiderx** [comment]
Hey, I will offer an enhanced build as soon as all current problems are eliminated. It will include wireguard. As of now you can just install it from luci after flashing the builds. 

Currently nss-ifb and SQM don't work correctly together

**Comment by markuznw** [comment]
Yeah, I also have an apparent "tx/rx hang" in these nss-wifi builds that makes playing a game impossible, it lags and timeouts quite often. Same goes on phone where you can notice a completely lock-up while loading. It resumes after 10-15 seconds.

**Comment by markuznw** [comment]
Can't seem to be able to install wg through opkg. It says there is no kmod-wireguard available. Do you use custom distfeeds?

**Comment by starraiderx** [comment]
> Yeah, I also have an apparent "tx/rx hang" in these nss-wifi builds that makes playing a game impossible, it lags and timeouts quite often. Same goes on phone where you can notice a completely lock-up while loading. It resumes after 10-15 seconds.

That mussed be your configuration. I can't replicate it. Please make sure when flashing you didn't keep an old config. Also please share logs If you encounter this issue again.

**Comment by starraiderx** [comment]
> Can't seem to be able to install wg through opkg. It says there is no kmod-wireguard available. Do you use custom distfeeds?

The problem is: src/gz openwrt_core https://openwrt.admincomps.ru/nss/20240218/packages

Caused by: https://github.com/qosmio/openwrt-ipq/commit/9c5068900457c52424cb526f0124c17797322cf0 which i dont have control over

**Comment by markuznw** [comment]
> > Can't seem to be able to install wg through opkg. It says there is no kmod-wireguard available. Do you use custom distfeeds?
> 
> The problem is: src/gz openwrt_core https://openwrt.admincomps.ru/nss/20240218/packages
> 
> Caused by: [qosmio/openwrt-ipq@9c50689](https://github.com/qosmio/openwrt-ipq/commit/9c5068900457c52424cb526f0124c17797322cf0) which i dont have control over

Yeah i tought that was the culprit, then I'll wait to see if you fork the packages repo into your own or add a static wg module :)
Thank you for your kindness. Will try to reset wireless config and re-create it meanwhile

**Comment by starraiderx** [comment]
Hey, I finished testing all NSS-related packages that are important and finalized my config.
I forgot that kmod packages are build dependent and won't work if you didn't build from the same repo they originated from. Which would be the case with Qosmio and "normal" OpenWrt.

Please just fork my repo and add CONFIG_PACKAGE_luci-proto-wireguard=y at the end of the config. It just compile you a working build within 1 hour

**Comment by bethnard** [comment]
Hi Julius,
I found your project after looking at the Openwrt forum and was amazed with the idea of automatic building the NSS image of my AX3600 on regular basis.
I also wanted to add WG and other packages to my build, so I forked your repo and committed some modifications to the AX3600.config file accordingly. However, I do not see any of the additional packages in the .manifest file generated after compilation.
Since I'm quite new to Github, could you please let me know if I'm doing anything wrong?
Thanks!

**Comment by JuliusBairaktaris** [comment]
Hey bethnard and welcome to Github,

Please rebase my repository (https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork). I hardcoded my own repository as the local repository as I was unaware that actions/checkout defaults to the local repository. This should be fixed now. 

It is also best practice to start your own issue, as your current problem is not related to @markuznw. 

Kind regards,
Julius

**Comment by bethnard** [comment]
Thanks for the quick feedback and support! :)

**Comment by JuliusBairaktaris** [comment]
You are welcome!
