### ISSUE TITLE
Can it support [Uboot] input?

### ISSUE THREAD

**Issue by GD2021** [JuliusBairaktaris/Qualcommax_NSS_Builder#2]
![image](https://github.com/JuliusBairaktaris/Qualcommax_NSS_Builder/assets/81171294/edc8d518-c938-48e0-a96c-2e6a12528281)
Uboot flashing unresponsive

**Comment by JuliusBairaktaris** [comment]
Its not supported:


[Don't use non-original uboot casually. I used to use other uboot and openwrt in my ax3600, and I got a brick.](https://forum.openwrt.org/t/qualcommax-nss-build/148529/1303)


But i never tried it myself. You can fork the repo and try yourself.

**Comment by mmmjie** [comment]
楼主有找到合适的固件吗？
之前我想装这个固件，试着把不死uboot还原成官方，结果还原的时候变砖了，找人修花了54......
现在刷好不死Uboot不敢还原了。。。

**Comment by JuliusBairaktaris** [comment]
As I understand it, you are trying to install this firmware after installing ImmortalWRT. The recommended method is as follows:

The recommended path is to reinstall the vendor/stock firmware and then switch to OpenWrt from there. This will avoid a situation where incorrect partition tables or other differences between the firmware in question could cause a brick.

The recovery method is described here: https://openwrt.org/toh/xiaomi/ax3600#tftp_recovery


-----------------------------------------------------------------------------------

Translation:

据我所知，您试图在安装 ImmortalWRT 之后再安装该固件。建议的方法如下：

建议的路径是重新安装供应商/库存固件，然后从那里切换到 OpenWrt。这将避免出现不正确的分区表或有关固件之间的其他差异导致卡机的情况。

恢复方法如下： https://openwrt.org/toh/xiaomi/ax3600#tftp_recovery


Hope that helps

**Comment by mmmjie** [comment]
> 据我了解，您正在尝试在安装 ImmortalWRT 后安装此固件。推荐方法如下：
> 
> 建议的路径是重新安装供应商/库存固件，然后从那里切换到 OpenWrt。这将避免错误的分区表或相关固件之间的其他差异可能导致变砖的情况。
> 
> 恢复方法描述如下：https://openwrt.org/toh/xiaomi/ax3600#tftp_recovery
> 
> 翻译：
> 
> 根据我的说法，您尝试在安装 ImmortalWRT 之后再安装该固件。建议的方法如下：
> 
> 建议的路径是重新安装供应商/库存固件，然后从那里切换到OpenWrt。这将避免出现不正确的分区表或有关固件之间的其他错误导致卡机的情况。
> 
> 恢复方法如下：https://openwrt.org/toh/xiaomi/ax3600#tftp_recovery
> 
> 希望有帮助

嗯。。十分感谢您的帮助
之前替我维修的工作人员说mtd 7的uboot分区损坏了，导致了无法修复

不管怎么说已经修复完毕了

原本我考虑是否要继续维修这个设备，毕竟已经好几年了

在思考后我让维修人员帮我维修，并且改了1G内存硬件，也许还能再跑几年？

主要我手上并没有ttl之类的维修设备，出现意外的时候需要寻求第三方人员帮助，这样成本会变高

有不死uboot无疑能替我磨平这个成本，但代价是无法使用一些未经修改的固件

请问您有如何将固件修改为支持不死uboot的教程吗？我可以试着自己看看

感谢您项目的分享

**Comment by JuliusBairaktaris** [comment]
> Do you have any tutorials on how to make firmware support undead uboot modifications? I can try to take a look myself.

I am unaware of such methods. 

I am not aware of such methods. 

The best IPQ807x for the price at the moment is the dynalink dl-wrx36. Its probably cheaper than upgrading the ram on the ax3600 and fixing it.

**Comment by jmwangde3** [comment]
https://github.com/immortalwrt/immortalwrt/pull/855/commits

可以参考下这个添加支持

**Comment by mmmjie** [comment]
我修改了个不死uboot版本的，不过内核指纹我不知道怎么指定上游一样的，要在安装后手动修改一次内核指纹，不然安装不了APP

https://github.com/mmmjie/Qualcommax_NSS_ax3600-uboot
