### ISSUE TITLE
Does this build include LuCI

### ISSUE THREAD

**Issue by sr229** [JuliusBairaktaris/Qualcommax_NSS_Builder#6]
Hello, I just wanna ask if this build includes LuCI, as I want to give this a shot on my current AX3600 router, but I have a custom configuration from firmware-selector, which I plan to bring over into a self-hosted ASU soon.

**Comment by JuliusBairaktaris** [comment]
Yes Luci is supported by default. You can check all pre installed packages here: https://github.com/JuliusBairaktaris/Qualcommax_NSS_Builder/blob/main/ax3600.config

**Comment by sr229** [comment]
> Yes Luci is supported by default. You can check all pre installed packages here: https://github.com/JuliusBairaktaris/Qualcommax_NSS_Builder/blob/main/ax3600.config

Thank you! Just a final question, firmware-selector seems to have changed their package selection in SNAPSHOT, is this reflected here too?

**Comment by JuliusBairaktaris** [comment]
Yes!
